### ISSUE TITLE
Add a link to the Carpentries Curriculum Development Handbook

### ISSUE THREAD

**Issue by annefou** [coderefinery/manuals#12]
I know it is not focused on CodeRefinery lesson design but I find it very helpful. I use a lot the Carpentries styles to create new lessons. 

https://cdh.carpentries.org/

I am happy to add the link if you think it is useful.

**Comment by bast** [comment]
Absolutely! This is a great handbook.

**Comment by bast** [comment]
Fixed in 79c27bb691171d71ef6dc3a92148ee410512ba54.
