### ISSUE TITLE
send email to participants 2-4 weeks before workshop

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/manuals#17]
currently we only send an email ~1 week before workshop with installation instructions. Now that we are filling up workshops many weeks in advance, maybe we should send an earlier email as well to confirm everyone's participation and send other general info. Here's an example of a few points from an email sent by a coinstructor for a software carpentry i'll be teaching:

1. If you are planning to attend, please confirm by replying to this email by DATE. If you won’t be able to attend, please let us know as well so that we can offer your seat to someone on the waiting list. [remind what the workshop is about and its level, so people who are too novice or too advanced might reconsider]

2. Be sure to complete the pre-workshop survey at URL, ideally by DATE. We use this to calibrate the pace of the workshop and, together with a post-workshop survey, to assess how it went.

3. Make sure you have the necessary software installed on your laptop; specifically X. Here are the instructions: URL. If you have any trouble, send us an email or come a little early on the morning of DATE. Someone will be there by 08:30 to help with installation issues. We also maintain a list of common issues that occur during installation that you can go through as well: https://github.com/carpentries/workshop-template/wiki/Configuration-Problems-and-Solutions

4. Please read our Code of Conduct (URL) so that we all are aware of how to treat each other respectfully. We are committed to making sure that the workshop is accessible to everyone. Please tell us if there is anything we should know in advance in order to make the workshop accessible for you

**Comment by bast** [comment]
Yes, I agree. It can be many weeks between registration and one week before and an earlier follow-up can help us to reduce waiting lists.
