### ISSUE TITLE
Needs a license...

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/manuals#6]
CC-BY-SA is used for other lessons.  Should these manuals be more liberal, CC-BY?  I'm happy with either.

Incidentally I saw that website repo doesn't have a license...

**Comment by rkdarst** [comment]
Actually the readme says CC-BY-SA.

**Comment by bast** [comment]
Both CC-BY and CC-BY-SA are fine for me.

**Comment by bast** [comment]
I will add a CC-BY-SA file to close the issue but I have nothing against making this more liberal.
